name: Split Monorepo
on:
  push:
    tags:
      - '*'
    branches:
      - 'master'
  release:
    types: [ created ]

jobs:
  generate-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - id: set-packages
        name: Generate Packages
        run: echo "packages=$(php tools/get-modified-packages.php | jq -c)" >> $GITHUB_OUTPUT

  split:
    needs: generate-packages
    if: ${{ needs.generate-packages.outputs.packages != '{"include":[]}' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-packages.outputs.packages) }}
    runs-on: 'ubuntu-latest'
    steps:
      -
        run: echo ${{ matrix.name }}
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: Split to repository
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          branch: 'master'
          package_directory: 'packages/${{ matrix.package_directory }}'
          repository_name: ${{ matrix.repository_name }}
          repository_organization: 'sxbrsky'
          user_email: 'dominikszamburski99@gmail.com'
          user_name: 'Dominik Szamburski'
